version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dplus/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user


hooks:
  AfterInstall:
    - location: stop.sh # nginx와 연결되지 않은 스프링 부트 종료.
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # nginx와 연결되어 있지 않은 포트로 스프링 부트 시작.
      timeout: 100
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 서비스 health check.
      timeout: 100
      runas: ec2-user
#  ApplicationStart:
#    - location: deploy.sh
#      timeout: 60
#      runas: ec2-user


#    - location: run_new_was.sh
#      timeout: 180
#      runas: ec2-user
#
#    - location: health_check.sh
#      timeout: 180
#      runas: ec2-user
#
#    - location: switch.sh
#      timeout: 180
#      runas: ec2-user
