spring:
  datasource:
    #h2 setting
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
#mysql setting
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # DB Source
#    url: jdbc:mysql://db-d-plus.c5giozjxeuua.ap-northeast-2.rds.amazonaws.com:3306/dpluswebservice
#    # DB username
#    username: admin
#    # DB password
#    password: dplus1212