cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: dplus-file-bucket
    region:
      static: ap-northeast-2

    credentials:
      accessKey: AKIA4LNITQAQOELAV2OY
      secretKey: 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