server:
  port: 8081

spring:
  config:
    activate:
      on-profile: real1
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB



  datasource:
    #mysql setting
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: ${rds.host}
    # DB username
    username: ${rds.username}
    # DB password
    password: ${rds.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: localhost

cloud:
  aws:
    s3:
      bucket: ${aws.s3.bucketname}
    #    region:
    #      static: ${aws.region.static}
    stack:
      auto: false
    credentials:
      accessKey: ${aws.s3.accesskey}
      secretKey: ${aws.s3.secretkey}
jwt:
  secret: ${jwt.secret}
  header: Authorization

logging.level:
  org.hibernate.SQL: debug

