name: DPlus-webservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          file: src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.RDS_HOST }}
          spring.datasource.username: ${{ secrets.RDS_USERNAME }}
          spring.datasource.password: ${{ secrets.RDS_PASSWORD }}
          jwt.secret: ${{ secrets.JWT_SECRET }}
          cloud.aws.credentials.accessKey: ${{secrets.AWS_S3_ACCESS_KEY}}
          cloud.aws.credentials.secretKey: ${{secrets.AWS_S3_SECRET_KEY}}
          cloud.aws.s3.bucket: ${{secrets.AWS_S3_BUCKET_NAME}}

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash